### ISSUE TITLE
Many reports of chatops does not respond back to the chat client

### ISSUE THREAD

**Issue by manasdk** [StackStorm/st2chatops#37] opened 2016-05-17 17:08 UTC
At times it is auth being disabled and issues connecting to st2stream, at times it is rule being disabled and at times it is a complete black box.

We need to close out a few of these holes as most of them sound like deployment issues.

**Comment by emedvedev** [comment] 2016-05-19 10:54
> at times it is rule being disabled

@lakshmi-kannan said that it's fixed in the latest unstable. I'll confirm today. Can reproduce this bug with stable on Ubuntu.

> issues connecting to st2stream

This happens when st2stream gets initialized after Hubot does, since Hubot can't reconnect and gives up. I'll try to reproduce (so far I couldn't), but it should be just a matter of adding an `st2ctl restart` at the end of our bootstrap script.

> auth being disabled
> complete black box

Need more info on those, but I'm on the lookout, and as soon as there's a bug I can reliably reproduce, I'll be pushing a fix asap.

It's better to file the bugs separately along with providing some context. Most of the issues (like rules) aren't chatops-related, just manifested there. I get that it's a sort of ragey meta-issue about how horrible things are, and I understand the frustration. 😛 Let's make things great again!

**Closed as completed by emedvedev** 2016-05-19 10:54 UTC
