### ISSUE TITLE
Installer fails with conflict of nodejs version even though it should succeed

### ISSUE THREAD

**Issue by wedgemartin** [StackStorm/st2chatops#107] opened 2018-04-17 18:38 UTC
el6:   Error: st2chatops conflicts with 2:nodejs-8.11.1-1nodesource.x86_64

**Comment by LindsayHill** [comment] 2018-04-17 18:41
Are you doing a manual install, following these instructions https://docs.stackstorm.com/install/rhel6.html ?

Looks like maybe you've added the NodeJS v8 repository, not the supported v6 one?

Could you provide the output of `yum list nodejs`?

**Comment by wedgemartin** [comment] 2018-04-17 18:41
Installed Packages
nodejs.x86_64                                                             2:8.11.1-1nodesource                                                              @nodesource    
Available Packages
nodejs.i686                                                               0.10.48-3.el6                                                                     Local-EPEL-Repo

**Comment by wedgemartin** [comment] 2018-04-17 18:42
Fastest response ever, btw.  Thank you.  Btw, we need this version of node for other stuff we're integrating here. I would expect that it wouldn't conflict since it's version is > 6

**Comment by LindsayHill** [comment] 2018-04-17 18:44
The packaging specifically needs a v6 version right now (no solid reason why it can't work with v8, but that needs testing). 

Are you running other things on that same server that require nodejs v8? Be cautious about running other stuff on the same VM. It's possible of course, but can run into conflicts...like this one.

**Comment by LindsayHill** [comment] 2018-04-17 19:01
This is the line in the spec file that explicitly calls out >= v7 as a conflict:

`Conflicts:      nodejs < 6.0, nodejs >= 2:7.0`

**Comment by LindsayHill** [comment] 2018-04-17 19:31
Closing this as it is working as designed. Installer should prevent install with newer nodejs versions.

**Closed as completed by LindsayHill** 2018-04-17 19:31 UTC

**Comment by blag** [comment] 2018-10-25 09:21
@wedgemartin I am working on updating the st2chatops package to work with nodejs versions 8 through 10 (inclusive). PR #116 might be of interest to you.

Also, there are quite a few restrictions on when to use the `Conflicts` field. In fact, the [Fedora documentation for it](https://fedoraproject.org/wiki/Packaging:Conflicts#Optional_Functionality) even calls out our exact usage as incorrect. So I will also be updating the packaging spec to only use the `Required` field and removing our usage of `Conflicts` entirely. I'm not 100% sure if that will allow you to force install newer versions of node than we officially support, but it should hopefully make it easier.

All of this work should be available with StackStorm 3.0.

**Comment by arm4b** [comment] 2018-10-25 14:43
This is expected behavior with `Conflicts`.

`st2chatops` package installation should fail if there is unsupported version of `nodejs` already exists/installed in the system.
